 name: pyaos-ams-2021
 channels:
   - conda-forge
 dependencies:
   - python=3.9
   - numpy
   - matplotlib
   - cartopy
   - metpy
   - siphon
   - pandas
   - xarray
   - ipywidgets
   - ffmpeg
   - boto3
   - jupyterlab
   - python-awips
   - xesmf>=0.5.0
   - xskillscore
