name: Lint Notebooks
on:
  push:
    branches: [master]
  pull_request:

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install flake8
        run: python -m pip install -r ci/linting_requirements.txt

      - name: Set up reviewdog
        run: |
          mkdir -p $HOME/bin
          curl -sfL \
            https://github.com/reviewdog/reviewdog/raw/master/install.sh | \
              sh -s -- -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run flake8
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flake8_nb notebooks/**/*.ipynb | reviewdog -f=pep8 -name=flake8 -reporter=github-check -filter-mode=nofilter
